runtime: custom
env: flex
entrypoint: gunicorn --bind 0.0.0.0:8080 app:app  # Change if your entry point is different

manual_scaling:
  instances: 1

resources:
  cpu: 4
  memory_gb: 8
  disk_size_gb: 20

